AllCops:
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
  Exclude:
    - config.ru
    - 'db/**/*'
    - 'script/*'
    - 'script/**/'
    - 'vendor/**/*'
    - 'config/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
Rails:
  Enabled: true
Metrics/ClassLength:
  Max: 150
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 60
Metrics/AbcSize:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/FileName:
  Exclude:
    - Gemfile
Style/Documentation:
  Exclude:
    - 'app/policies/*'
Style/Lambda:
  EnforcedStyle: literal
