AllCops:
  Include:
    - Rakefile
  Exclude:
    - config.ru
    - 'db/**/*'
    - 'script/*'
    - 'script/**/'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
